//! JVM methods.

use bitflags::bitflags;

use super::{Method, references::MethodRef};
use crate::intrinsics::see_jvm_spec;
use crate::types::reference_type::ReferenceType;

/// A generic type signature for a method.
pub type Signature = String;

impl Method {
    /// The method of a static initializer block.
    pub const CLASS_INITIALIZER_NAME: &'static str = "<clinit>";
    /// The method of a constructor.
    pub const CONSTRUCTOR_NAME: &'static str = "<init>";

    /// Checks if the method is a constructor.
    #[must_use]
    pub fn is_constructor(&self) -> bool {
        self.name == Self::CONSTRUCTOR_NAME
    }

    /// Checks if the method is a static initializer block.
    #[must_use]
    pub fn is_static_initializer_block(&self) -> bool {
        self.name == Self::CLASS_INITIALIZER_NAME
    }

    /// Creates a [`MethodRef`] pointting to this method.
    #[must_use]
    pub fn as_ref(&self) -> MethodRef {
        MethodRef {
            owner: ReferenceType::Class(self.owner.clone()),
            name: self.name.clone(),
            descriptor: self.descriptor.clone(),
        }
    }
}

/// The information of a method parameter.
#[doc = see_jvm_spec!(4, 7, 24)]
#[derive(Debug, Clone)]
pub struct ParameterInfo {
    /// The name of the parameter.
    pub name: Option<String>,
    /// The access flags of the parameter.
    pub access_flags: ParameterAccessFlags,
}

bitflags! {
    /// Access flags for a [`Method`].
    #[doc = see_jvm_spec!(4, 6)]
    #[derive(Debug, PartialEq, Eq, Clone, Copy)]
    pub struct AccessFlags: u16 {
        /// Declared `public`; may be accessed from outside its package.
        const PUBLIC = 0x0001;
        /// Declared `private`; accessible only within the defining class and other classes belonging to the same nest.
        const PRIVATE = 0x0002;
        /// Declared `protected`; may be accessed within subclasses.
        const PROTECTED = 0x0004;
        /// Declared `static`.
        const STATIC = 0x0008;
        /// Declared `final`; must not be overridden.
        const FINAL = 0x0010;
        /// Declared `synchronized`; invocation is wrapped by a monitor use.
        const SYNCHRONIZED = 0x0020;
        /// A bridge method, generated by the compiler.
        const BRIDGE = 0x0040;
        /// Declared with variable number of arguments.
        const VARARGS = 0x0080;
        /// Declared `native`; implemented in a language other than Java.
        const NATIVE = 0x0100;
        /// Declared `abstract`; no implementation is provided.
        const ABSTRACT = 0x0400;
        /// In a `class` file whose major version is at least 46 and at most 60; Declared `strictfp`.
        const STRICT = 0x0800;
        /// Declared synthetic; not present in the source code.
        const SYNTHETIC = 0x1000;
    }
}

bitflags! {
    /// The access flags for a method parameter.
    #[doc = see_jvm_spec!(4, 7, 24)]
    #[derive(Debug, PartialEq, Eq, Clone, Copy)]
    pub struct ParameterAccessFlags: u16 {
        /// Declared `final`; may not be assigned to after initialization.
        const FINAL = 0x0010;
        /// Declared synthetic; not present in the source code.
        const SYNTHETIC = 0x1000;
        /// Declared as either `mandated` or `optional`.
        const MANDATED = 0x8000;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::jvm::code::Instruction;

    #[test]
    fn special_method_checks_use_only_the_name() {
        let mut method = crate::tests::method(
            [(0, Instruction::Return)],
            "()V",
            vec![],
            AccessFlags::PUBLIC,
        );
        for (name, constructor, initializer) in [
            (Method::CONSTRUCTOR_NAME, true, false),
            (Method::CLASS_INITIALIZER_NAME, false, true),
            ("ordinary", false, false),
        ] {
            method.name = name.to_owned();
            assert_eq!(
                (
                    method.is_constructor(),
                    method.is_static_initializer_block()
                ),
                (constructor, initializer),
            );
        }
    }
}
